// ===== FI locale (generated by tools/translate-fi.mjs from js/en/data.js — do not edit by hand) =====
const VDIR = "videos/";
const VID = {
 "V1": "Fitness_TC_Mobility_1-13_premium.mp4",
 "V2": "Fitness_TC_Core_1-9_premium.mp4",
 "V3": "Fitness_Colbert_Lower_Body_Strenght_1-8_premium.mp4",
 "V4": "Fitness_TC_Explosivity_1-6_premium.mp4",
 "V5": "Core_progressions_all_exercises_premium.mp4"
};
const VREMOTE = {
 "V1": "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-dynamic-mobility.php"
};
const VIDMETA = [
 {
  "v": "V1",
  "title": "Dynaaminen liikkuvuusharjoittelu – kaikki 13 liikettä",
  "note": "Videoissa 1–13 on sama järjestys kuin alla olevassa Mobility-kirjastossa. Videot on isännöity FIFA:n sivustolla (tiedosto on liian suuri GitHubiin)."
 },
 {
  "v": "V2",
  "title": "Vahva keskivartalo – kaikki 9 liikettä",
  "note": "Videoiden järjestys on 1–9, mikä vastaa alla olevaa Core-kirjastoa."
 },
 {
  "v": "V3",
  "title": "Toiminnallinen alavartalon voimaharjoittelu – kaikki 8 liikettä",
  "note": "Videoissa 1–8 esitellään alla olevan alavartaloharjoitusohjelman liikkeet."
 },
 {
  "v": "V4",
  "title": "Räjähtävä voima – kaikki 6 harjoitusta",
  "note": "Videoissa 1–6 on sama järjestys kuin alla olevassa Explosivity-kirjastossa."
 },
 {
  "v": "V5",
  "title": "Keskivartalo – uusia harjoituksia ja variaatioita (7)",
  "note": "Videoissa 1–7 esitetään seuraavat perusprogressiot."
 }
];
const SOURCES = [
 [
  "Perusta fyysiselle kehitykselle",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-foundation-for-phyiscal-development.php"
 ],
 [
  "Saavuta enemmän vähemmällä (älykäs harjoittelu)",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-building-more-from-less.php"
 ],
 [
  "Dynaaminen liikkuvuus",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-dynamic-mobility.php"
 ],
 [
  "Vahva keskivartalo",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-core-strength.php"
 ],
 [
  "Alavartalon toiminnallinen voima",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-functional-lower-body-strength.php"
 ],
 [
  "Räjähtävyys",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-explosivity.php"
 ],
 [
  "Perusliikkeet: uusia harjoituksia ja variaatioita",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-core-strength-progressions.php"
 ],
 [
  "Liikkuvuus ja voima: uusia harjoituksia ja niiden asteittaista kehittämistä",
  "https://www.fifatrainingcentre.com/en/practice/training-perspectives/athleticism-for-young-players/athleticism-for-young-players-mobility-and-strength-progressions.php"
 ]
];
const EX = {
 "m01": {
  "n": "Sammakkoasento",
  "p": "mobility",
  "v": [
   "V1",
   1
  ],
  "focus": "Lonkan koukistajat, lähentäjät, kiertäjät",
  "cues": [
   "Pidä jalat vaakasuorassa ulospäin koko ajan."
  ],
  "prog": "Lisää kierto (m02)"
 },
 "m02": {
  "n": "Sammakkoasento kierrolla",
  "p": "mobility",
  "v": [
   "V1",
   2
  ],
  "focus": "Lonkan sisäkiertäjät",
  "cues": [
   "Nosta jalka.",
   "Purista pakaralihakset yhteen ja pidä hetki ylhäällä."
  ],
  "prog": "—"
 },
 "m03": {
  "n": "Polviasennossa tehtävä sisäreiden venytys",
  "p": "mobility",
  "v": [
   "V1",
   3
  ],
  "focus": "Lonkan sisäkiertäjät ja ulkokiertäjät",
  "cues": [
   "Jännitä jalkaa suoraksi, jalkapohja koskettaa lattiaa kokonaan.",
   "Pidä venytysasentoa hetken aikaa täydessä liikeradassa ennen paluuta."
  ],
  "prog": "—"
 },
 "m04": {
  "n": "Kyyhkysvenytys ulkokierrolla",
  "p": "mobility",
  "v": [
   "V1",
   4
  ],
  "focus": "Lonkan koukistajat ja ulkokierto­lihakset",
  "cues": [
   "Nosta polvi mahdollisimman ylös.",
   "Pidä hetken yläasennossa."
  ],
  "prog": "—"
 },
 "m05": {
  "n": "90-90-siirtymä",
  "p": "mobility",
  "v": [
   "V1",
   5
  ],
  "focus": "Lonkan sisä- ja ulkokierto",
  "cues": [
   "Istukaa mahdollisimman suorassa asennossa ja vaihtakaa asentoa säännöllisesti."
  ],
  "prog": "Lisää käden ojennusliike / lantionnosto (katso keskivartalon harjoitukset)."
 },
 "m06": {
  "n": "Suorakätälankku → pitkä askel",
  "p": "mobility",
  "v": [
   "V1",
   6
  ],
  "focus": "Aktivoituneet lonkan koukistaja-/ojentajalihakset + vahva keskivartalo",
  "cues": [
   "Kädet täysin suorina, rinta ulospäin.",
   "Älä anna lantion laskeutua lankkuasennossa, jossa vartalo on tuettu kyynärvarsien ja jalkaterien varassa.",
   "Takajalka on ojentunut ja irti lattiasta."
  ],
  "prog": "—"
 },
 "m07": {
  "n": "Lankusta suorajalkainen lonkan koukistus ja lähennys",
  "p": "mobility",
  "v": [
   "V1",
   7
  ],
  "focus": "Aktiivinen lonkan koukistus ja lähentäminen, keskivartalon lihasten ollessa aktiivisia",
  "cues": [
   "Kosketa varpailla lattiaa hallitusti ja vie jalka ulospäin.",
   "Kädet suorina vartalon sivuilla, rinta ulospäin, lantio vaakasuorassa."
  ],
  "prog": "—"
 },
 "m08": {
  "n": "Juoksija-askel → takareiden siirto",
  "p": "mobility",
  "v": [
   "V1",
   8
  ],
  "focus": "Lonkan koukistajat/ojentajat, alaselkä",
  "cues": [
   "Palautu neutraaliin asentooon askelkyykyn jälkeen.",
   "Kallistu hieman eteenpäin lantiosta, ota jänne-asento, pidä rinta ulkona ja pää ylhäällä.",
   "Suora jalka, varpaat kohti säärtä."
  ],
  "prog": "—"
 },
 "m09": {
  "n": "Pään yläpuolella tehtävä kyykky (kädet ylhäällä, ei tankoa)",
  "p": "mobility",
  "v": [
   "V1",
   9
  ],
  "focus": "Lonkan ojentajat/ulkopyörittäjät, selkäranka, nilkat, olkapäät + keskivartalo",
  "cues": [
   "Jalat ovat leveämmät kuin hartiat.",
   "Kädet täysin suorina ylhäällä",
   "Istu syvälle, pidä rinta ylhäällä, vatsalihakset jännitettynä ja pää koholla."
  ],
  "prog": "—"
 },
 "m10": {
  "n": "Sumokyykky vuorotellen eteenpäin ulottuen",
  "p": "mobility",
  "v": [
   "V1",
   10
  ],
  "focus": "Lonkan ojentajat/ulkokiertäjät + selkärangan kierto",
  "cues": [
   "Istu syvälle, jalat tukevasti lattiaa vasten.",
   "Nosta kätesi ylös ja pyöritä, katso ulottuvaa kättä.",
   "Vie polvet ulospäin."
  ],
  "prog": "—"
 },
 "m11": {
  "n": "Polviasennossa tehtävä askelkyykky kierrolla",
  "p": "mobility",
  "v": [
   "V1",
   11
  ],
  "focus": "Selän kiertajalihakset, lonkan lähentäjät/koukistajat",
  "cues": [
   "Vakaa askel, etummainen polvi osoittaa suoraan eteenpäin.",
   "Käänny 180 astetta sivuttain, kädet ojennettuina hartian korkeudelle.",
   "Käännä päätäsi ja katso takasauvaa pitkin."
  ],
  "prog": "—"
 },
 "m12": {
  "n": "Vuorottainen sivuaskelkyykky",
  "p": "mobility",
  "v": [
   "V1",
   12
  ],
  "focus": "Lonkan sisäkiertäjät/ulkokiertäjät, nilkat + keskivartalo",
  "cues": [
   "Selkä suorana, rinta ulos, pää ylhäällä.",
   "Ylävartalo linjassa eteenpäin ojentavan polven kanssa.",
   "Molempien jalkojen päkiät pysyvät lattialla."
  ],
  "prog": "Pidä kevyttä painoa suorilla käsivarsilla (P3+)."
 },
 "m13": {
  "n": "Maailman paras venyttelyharjoitus",
  "p": "mobility",
  "v": [
   "V1",
   13
  ],
  "focus": "Lantio + vartalon kierto + hartiat + keskivartalo",
  "cues": [
   "Pitkä askel eteenpäin, takajalka irti lattiasta, lantio ei saa laskeutua.",
   "Tukikäsi on samalla linjalla kuin etujalka.",
   "Pyöritä ja kurkota ylös suuressa kaaressa, pidä asento hetken."
  ],
  "prog": "—"
 },
 "c01": {
  "n": "Makaava isometrinen pito (lankku)",
  "p": "core",
  "v": [
   "V2",
   1
  ],
  "focus": "Syvät vatsalihakset, olkapään alue",
  "cues": [
   "Suora linja päästä varpaisiin.",
   "Purista pakaralihakset, älä anna lantion roikkua tai notkua."
  ],
  "prog": "Lankkuasento vuorotellen yläraajojen ojennuksella (c02)"
 },
 "c02": {
  "n": "Lankkuasento, vuorotellen toisen käden ojentaminen eteen",
  "p": "core",
  "v": [
   "V2",
   2
  ],
  "focus": "Vahva keskivartalo + vartalon kierto + olkapään vakaus",
  "cues": [
   "Ojenna käsi eteenpäin hartian korkeudelle.",
   "Älä kierrä vartaloa ylösnostetun käden suuntaan; pidä lantio vaakasuorassa."
  ],
  "prog": "Hämähäkkimies kiipeää (c10)"
 },
 "c03": {
  "n": "Vaihteleva supermies",
  "p": "core",
  "v": [
   "V2",
   3
  ],
  "focus": "Selän ojentajalihakset, pakaralihakset, kylkilihakset",
  "cues": [
   "Vuorotellen käsi ylös ja vastakkainen jalka ylös.",
   "Pidä vaakasuora viiva",
   "Aktivoi kohotetun jalan pakaralihas."
  ],
  "prog": "Pysy yläasennossa 3–5 sekuntia."
 },
 "c04": {
  "n": "Pakara-takareisinosto",
  "p": "core",
  "v": [
   "V2",
   4
  ],
  "focus": "Lonkan ja selkärangan ojentajalihakset",
  "cues": [
   "Samanaikainen suoran jalan nosto ja koukun jalan ojennus",
   "Pidä hetken yläasennossa.",
   "Molemmat jalat toimivat yhdessä, ja niiden liikkeitä säädellään."
  ],
  "prog": "Hartiat laatikolla, yhden jalan variaatio P4:ssä (x05)"
 },
 "c05": {
  "n": "Korkea polvennosto -marssi (paikallaan)",
  "p": "core",
  "v": [
   "V2",
   5
  ],
  "focus": "Vahva keskivartalo + lonkan koukistajalihakset, nilkan vakaus",
  "cues": [
   "Kädet suorina lukittuina pään yläpuolelle.",
   "Nosta polvet ylös ja kävele ryhdikkäästi."
  ],
  "prog": "Kävely → kävely → polviasennosta eteenpäin laskeutuminen ja kävely"
 },
 "c06": {
  "n": "Sivulankku, jalat yhdessä",
  "p": "core",
  "v": [
   "V2",
   6
  ],
  "focus": "Lonkan loitontajat, kylkilihakset, selän ojentajalihakset",
  "cues": [
   "Lantio eteen ja ylös, ryhti suorana.",
   "Jalkaterät koukistettu ylöspäin (varpaat kohti sääriä)"
  ],
  "prog": "Jalat erilleen (c07) → ulottuvuus (c11)"
 },
 "c07": {
  "n": "Sivulankku, jalat erillään",
  "p": "core",
  "v": [
   "V2",
   7
  ],
  "focus": "Sama liikeketju, leveämpi pohja = suurempi kuormitus vinoille vatsalihaksille ja lonkan loitontajalihaksille.",
  "cues": [
   "Suora linja, lantio ylhäällä.",
   "Jalat ovat leveämmällä kuin sivulankkuasennossa."
  ],
  "prog": "Nosta yläjalka ja pidä hetki; avoin sivulankku (c12)"
 },
 "c08": {
  "n": "Istuessa vuorotellen jalkojen nosto",
  "p": "core",
  "v": [
   "V2",
   8
  ],
  "focus": "Lonkan koukistajat, syvät vatsalihakset, selän ojentajalihakset",
  "cues": [
   "Selkä suorana, pää ylhäällä.",
   "Suora jalka, lyhyt pito yläasennossa"
  ],
  "prog": "Vähemmän käsivarsitukea → yksi käsi → ei käsiä"
 },
 "c09": {
  "n": "Kööpenhaminan lankku",
  "p": "core",
  "v": [
   "V2",
   9
  ],
  "focus": "Lonkan sisäkiertajalihakset, kylkilihakset",
  "cues": [
   "Yläosan jalan tukipiste sijaitsee aivan yläpolven alapuolella.",
   "Seiso suorana, rinta ulkona, lantio edessä."
  ],
  "prog": "Laske ja nosta lantio (c16). Helpotus ensin: työskentelevä jalka lattialla"
 },
 "c10": {
  "n": "Spiderman-kiipeily: polvi kyynärpäähän",
  "p": "core",
  "v": [
   "V5",
   1
  ],
  "focus": "Syvät vatsalihakset, vino lihakset, lonkan koukistajat, olkapään lihasryhmä",
  "cues": [
   "Aloita kyynärnoja-asennosta.",
   "Kosketa vuorotellen vasenta ja oikeaa kyynärpäätä vastaavalla polvella.",
   "Lantio ei saa kiertyä – vartalon tulee olla suorassa päästä varpaisiin."
  ],
  "prog": "Hitaampi tempo, laajempi ääniala."
 },
 "c11": {
  "n": "Sivulankku, jossa käsi ojennetaan vartalon läpi (kiertoliike)",
  "p": "core",
  "v": [
   "V5",
   2
  ],
  "focus": "Lonkan loitontajat, kylkilihakset, lannerangan/rintarangan kiertäjät",
  "cues": [
   "Lantio eteenpäin, suora ryhti, jalat koukussa",
   "Vie käsi vartalon alle suuressa kaaressa, kunnes se on täysin ojennettu ylös."
  ],
  "prog": "—"
 },
 "c12": {
  "n": "Avoin sivulankku: käden ja lonkan koukistus/ojennus",
  "p": "core",
  "v": [
   "V5",
   3
  ],
  "focus": "Vahva keskivartalo ja lantion koordinaatio, vino vatsalihas, lonkan loitontajat",
  "cues": [
   "Kyynärpää polveen, sitten polvi kyynärpäähän.",
   "Venytä, kunnes olet täysin suorassa asennossa, jalat leveällä."
  ],
  "prog": "—"
 },
 "c13": {
  "n": "Kyykkyasennossa tehtävät vuorottain lantion kierrot käsien nostojen kanssa.",
  "p": "core",
  "v": [
   "V5",
   4
  ],
  "focus": "Lonkan ja alaselän kiertäjät, vino lihas, yksipuolinen tasapaino",
  "cues": [
   "Kierrä alavartaloa lattiaa kohti, tue itseäsi yhdellä kädellä.",
   "Pidä hetken aikaa molempia puolia, älä pidätä hengitystä."
  ],
  "prog": "—"
 },
 "c14": {
  "n": "Istuva pakaroiden nosto ja vastuksella tehtävä lantionnosto",
  "p": "core",
  "v": [
   "V5",
   5
  ],
  "focus": "Lonkan ojentajat/ulkokiertäjät, syvät vatsalihakset, alaselän tukilihakset",
  "cues": [
   "Laskeudu hitaasti, kosketa kevyesti lantiolla lattiaa.",
   "Työnnä lantiota eteenpäin samalla kun nostat sitä ylöspäin, pidä paino tasaisesti lantiolla."
  ],
  "prog": "Kevyt reppu lantiolla (U10: täytetty reppu)"
 },
 "c15": {
  "n": "90-90-kiertoja yhdistettynä lantionnostoihin",
  "p": "core",
  "v": [
   "V5",
   6
  ],
  "focus": "Lannerangan kiertäjät, lonkan ojentajat, syvät keskivartalon lihakset",
  "cues": [
   "Kierrä 90-90 vasen/oikea, nouse räjähdysmäisesti pystyyn jokaisen kierron lopuksi",
   "Suora lanneranka, rinta ulospäin, pää ylhäällä."
  ],
  "prog": "—"
 },
 "c16": {
  "n": "Kööpenhaminan lankku: lasku ja nousu",
  "p": "core",
  "v": [
   "V5",
   7
  ],
  "focus": "Lonkan sisäkiertäjät, vatsalihakset, selkärangan tukilihakset",
  "cues": [
   "Laske alempi lonkka hitaasti lattiaan ja ponnista sitten takaisin ylös.",
   "Rinta eteen, lantio eteen, käsi voi ulottua alaspäin → ylös"
  ],
  "prog": "—"
 },
 "l01": {
  "n": "Askelkyykky / staattinen askelkyykky",
  "p": "lbs",
  "v": [
   "V3",
   1
  ],
  "focus": "Nelipäiset reisilihakset, pakaralihakset, takareisilihakset, syvät keskivartalon lihakset",
  "cues": [
   "Pää ylhäällä, selkä suorassa.",
   "Laskeudu, kunnes takareiden polvi koskettaa kevyesti maata.",
   "Työnnä jalkaa eteenpäin keskiosasta."
  ],
  "prog": "Aseta etujalka alimman tikkaan askelman päälle; → peruuta askel taaksepäin (l02)"
 },
 "l02": {
  "n": "Vuorotellen tehtävä taaksepäin suuntautuva askelkyykky",
  "p": "lbs",
  "v": [
   "V3",
   2
  ],
  "focus": "Sama ketju + tasapaino/vakaus",
  "cues": [
   "Ota askeleen taaksepäin ja hallitse tilanne, älä anna periksi.",
   "Pidä ylävartalo suorana koko liikkeen ajan."
  ],
  "prog": "Pidä kevyttä laukkua olkapään korkeudella (P3+)."
 },
 "l03": {
  "n": "Pään-yläpuolella-takaskelkyykky + ojennus",
  "p": "lbs",
  "v": [
   "V3",
   3
  ],
  "focus": "Askelkyykky + ylävartalon vakautus, keskivartalo",
  "cues": [
   "Kädet pidetään koko ajan ylhäällä.",
   "Sujuva ja hallittu askel taaksepäin"
  ],
  "prog": "Yhden käden yläpuolinen ulottuvuus"
 },
 "l04": {
  "n": "Bulgarialainen askelkyykky (takajalka tikkailla)",
  "p": "lbs",
  "v": [
   "V3",
   4
  ],
  "focus": "Yksipuolinen alaraajojen voima",
  "cues": [
   "Takajalka tikkaan askelmalla",
   "Kallista jalkaa hieman eteenpäin ja paina jalkaterän keskiosalla."
  ],
  "prog": "Pienennä askelpituutta = suurempi liikerata."
 },
 "l05": {
  "n": "Yksijalkainen luistelijakyykky (laatikolle)",
  "p": "lbs",
  "v": [
   "V3",
   5
  ],
  "focus": "Yhden jalan voima + tasapaino",
  "cues": [
   "Kyykisty alas yhdellä jalalla kohti laatikkoa.",
   "Napauta/aseta kohdekorkeudelle ja vedä takaisin samalla liikkeellä."
  ],
  "prog": "Laske laatikko vähitellen lattiaa kohti."
 },
 "l06": {
  "n": "Muunnettu pistol-kyykky (laatikolle)",
  "p": "lbs",
  "v": [
   "V3",
   6
  ],
  "focus": "Yhden jalan voima koko liikeradalla",
  "cues": [
   "Kädet sivuille, vapaa jalka suorana irti lattiasta.",
   "Istu takaisin laatikolle ja nouse ylös ilman, että pomppaat kahdesti."
  ],
  "prog": "Laske laatikko alemmas; pidä vapaa jalka irti lattiasta. Helpompi: vapaa kantapää koskettaa lattiaa."
 },
 "l07": {
  "n": "Yhdellä jalalla tehtävä askel alas (laatikolta)",
  "p": "lbs",
  "v": [
   "V3",
   7
  ],
  "focus": "Yhdellä jalalla tasapainottaminen, laskeutumisen vakauttaminen",
  "cues": [
   "Laske alempi jalka hitaasti alas niin, että se koskettaa kevyesti lattiaa hallitusti.",
   "Polvet liikkuvat varpaiden yli, lantio on vaakasuorassa."
  ],
  "prog": "Nosta jalkaa korkeammalle; liu’uta vapaa jalka eteenpäin koskettaessa."
 },
 "l08": {
  "n": "Vuorottainen sivuaskelkyykky (vahvuusversio)",
  "p": "lbs",
  "v": [
   "V3",
   8
  ],
  "focus": "Sivuttaistaso – lähentäjät/loitontajat",
  "cues": [
   "Selkä suorana, rinta ulospäin, kyynärpäät ylhäällä.",
   "Istu syvälle, molemmat jalat lattialla."
  ],
  "prog": "Pidä kevyttä laukkua suorilla käsivarsilla."
 },
 "p01": {
  "n": "Sprintterin tehokkaat askeleet vahvoilla käsivarsilla",
  "p": "power",
  "v": [
   "V4",
   1
  ],
  "focus": "Täydellinen lineaarinen tehosarja",
  "cues": [
   "Lineaarisen liikkeen laatu on ensisijaisen tärkeää.",
   "Työnnä voimakkaasti käsillä.",
   "Lyhyt pysähdys toiminta-alueen lopussa."
  ],
  "prog": "Sprinttihyppy; bulgarialainen askelhyppy"
 },
 "p02": {
  "n": "Kaksijalkainen laatikkohyppy, jäykät jalat + käsien työnnys",
  "p": "power",
  "v": [
   "V4",
   2
  ],
  "focus": "Nilkan, polven ja lonkan ojentajalihakset",
  "cues": [
   "Aseta asento, tee vain pieni vastaliike.",
   "Aja laatikon päälle ja pysäytä auto rauhallisesti."
  ],
  "prog": "Lisää korkeutta (matto laatikon takana); yhden jalan hyppy alhaisesta korkeudesta"
 },
 "p03": {
  "n": "Kaksijalkainen laatikkohyppy kierrolla",
  "p": "power",
  "v": [
   "V4",
   3
  ],
  "focus": "Sama + lantion/selkärangan kierto laskeutumisen aikana",
  "cues": [
   "Sama kuin laatikkoon hyppääminen, kierrä vartaloa niin, että laskeudut kasvot käännettynä käännöksen suuntaan.",
   "Maa on hiljainen, pysy siinä."
  ],
  "prog": "Suuremmat pyörimisnopeudet sallitaan vain, kun laskut ovat pehmeitä."
 },
 "p04": {
  "n": "Kaksijalkainen pituushyppy vastaliikkeellä",
  "p": "power",
  "v": [
   "V4",
   4
  ],
  "focus": "Vaakasuora teho",
  "cues": [
   "Aseta → voimahyökkääjä, jotta saat maksimaalisen kantaman.",
   "Nopea taaksepäin suuntautuva vastaliike, jonka jälkeen liikutaan jälleen eteenpäin (1–2 toistoa peräkkäin)."
  ],
  "prog": "Yhden jalan ponnistushypyt (P4, 2–3 toistoa)"
 },
 "p05": {
  "n": "Yksijalkaiset sivuttaiset vastahypyt V↔O (kevyt kuorma)",
  "p": "power",
  "v": [
   "V4",
   5
  ],
  "focus": "Sivuttaisliike + yhden jalan voimantuotto, laskeutumisen vakauttajat",
  "cues": [
   "Aja sivusuunnassa saadaksesi mahdollisimman suuren etäisyyden.",
   "Nopea paluunäppäin alkuun",
   "U10 kuorma = vain kevyt reppu, ja vain tyhjänä se on puhdas."
  ],
  "prog": "Lisääntynyt kierto (kädet ulottuvat laskeutumislinjan ulkopuolelle)"
 },
 "p06": {
  "n": "Yksijalkainen sivuttainen vastatoisto, kuormaton, nopea",
  "p": "power",
  "v": [
   "V4",
   6
  ],
  "focus": "Laskeutumisnopeus + sivuttaisasetuksen palautus",
  "cues": [
   "Painotetaan laskeutumisen ja vastaliikkeen NOPEUTTA.",
   "Kädet liikkuvat linjan ulkopuolella."
  ],
  "prog": "Nopeampi laskuri – ei koskaan kovempaa ääntä laskeutuessa."
 },
 "x01": {
  "n": "Curtsy-kyykky → sivuaskelkyykky",
  "p": "combo",
  "v": null,
  "focus": "Polven ja lantion ojentajat, pakaralihaksen mediaaliosa (koukistavan jalan puolella), sisäkiertäjät + syvät keskivartalon lihakset",
  "cues": [
   "Tee suuri askel sivulle, pidä toinen jalka suorana.",
   "Risti takajalka toisen yli, polvi kohti lattiaa jalan etuosan päällä.",
   "Vie paino ylöspäin sivuttaisaskeleen aikana.",
   "U10: Aloita omalla painolla; käytä vastusta (apuri tai pussi) vain rintakehän korkeudella, ja vasta kun liike on täydellinen."
  ],
  "prog": "Lisää kevyt vastus, kun kehonpainoharjoittelu sujuu hyvin."
 },
 "x02": {
  "n": "Eteenaskel vartalon kierrolla",
  "p": "combo",
  "v": null,
  "focus": "Nelipäiset reisilihakset, pakaralihakset, syvät vatsalihakset, lannerangan kiertajalihakset",
  "cues": [
   "Pää ylhäällä, rinta ulkona, selkä suorana.",
   "Kierrä ylävartaloa koukussa olevilla käsivarsilla rintakehän korkeudella ja käännä päätä käsien avulla.",
   "Kevyt polven kosketus, ponnista ylöspäin käyttäen pakaralihaksia ja keskivartalon kiertäjiä."
  ],
  "prog": "Lisää kevyt vastus, kun kehonpainoharjoittelu sujuu hyvin."
 },
 "x03": {
  "n": "Yksijalkainen romanialainen maastaveto (pillar-tuki)",
  "p": "combo",
  "v": null,
  "focus": "Lonkan ojentajalihakset, alaselän ojentajalihakset, tasapaino",
  "cues": [
   "Käänny lantiosta, pidä alaselkä suorana ja takajalka suorana takana.",
   "Nosta kädet ylös yhdellä liikkeellä, vie ne rintaan ja ojenna sitten täysin."
  ],
  "prog": "Pieni kuorma, vakaa ja hallittu käynnistys alusta loppuun."
 },
 "x04": {
  "n": "Korkea eteenaskel + kierto yläojennuksella",
  "p": "combo",
  "v": null,
  "focus": "Nelipäiset reisilihakset, pakaralihakset, lannerangan/rintarangan kiertajalihakset (kiihtyvyys → hidastuvuus)",
  "cues": [
   "Aloita riittävän kaukaa laatikosta/korokkeesta, jotta et joudu kurkottamaan liikaa.",
   "Voimakas ponnistus takareidestä ja polvesta, jalka nousee korkealle.",
   "Viimeistele voimakkaalla, pyörivällä ylävartalon liikkeellä."
  ],
  "prog": "Edellytys: x02 on hallittava. Lisää myöhemmin kevyempi kuorma."
 },
 "x05": {
  "n": "Yhdellä jalalla tehtävä pakara-takareisi -liike, hartiat laatikolla.",
  "p": "combo",
  "v": null,
  "focus": "Pakara-, selkälihakset ja poikittaiset vatsalihakset",
  "cues": [
   "Makaa vaakasuorassa, hartiat laatikon/patjan reunalla.",
   "Ojenna työstettävä jalka täysin samalla kun taivutat vapaan jalan lonkkaa, pidä asento hetken."
  ],
  "prog": "Kevyt vastus työstettävän jalan lonkan kohdalla."
 },
 "x06": {
  "n": "Punnerrus + kierto",
  "p": "combo",
  "v": null,
  "focus": "Ylävartalo + rinta- ja selkälihasten kiertäjät, koko keskivartalo",
  "cues": [
   "Paina ylöspäin ja pyöritä vartaloa niin, että kädet nousevat ylös suurikuvioisessa kaaressa ja suoristuvat taaksepäin.",
   "Hallitse laskeutumista – älä anna painon pudota."
  ],
  "prog": "Aluksi ei vastusta; käytä vain pieniä käsipainoja, kun selkä pysyy suorana."
 }
};
const WUS = {
 "A": {
  "name": "Sarja A – lantion ja selkärangan perusliikkeet (vaihe 1)",
  "ex": [
   "m09",
   "m03",
   "m04",
   "m05",
   "m08",
   "m10",
   "m11",
   "m12"
  ]
 },
 "B": {
  "name": "Sarja B – lisää liikkuva vakaus (vaihe 2)",
  "ex": [
   "m02",
   "m05",
   "m11",
   "m06",
   "m12",
   "m08",
   "m10",
   "m07",
   "m13"
  ]
 },
 "C": {
  "name": "Sarja C – koko paketti (vaiheet 3–4)",
  "ex": [
   "m09",
   "m10",
   "m06",
   "m07",
   "m13",
   "m05",
   "m11",
   "m04",
   "m01"
  ]
 }
};
const MENUS = {
 "coreBase1": {
  "name": "Ydin 1 – vakauden perusta",
  "kind": "core",
  "rounds": "2 kierrosta",
  "rest": "45 sekuntia lepoa liikkeiden välillä, 90 sekuntia lepoa kierrosten välillä.",
  "ex": [
   {
    "id": "c01",
    "dose": "Pidä 20–30 sekuntia."
   },
   {
    "id": "c06",
    "dose": "15–20 sekuntia / puoli"
   },
   {
    "id": "c04",
    "dose": "8 toistoa"
   },
   {
    "id": "c05",
    "dose": "20 sekuntia, nopea marssi"
   },
   {
    "id": "c08",
    "dose": "8 / jalka"
   },
   {
    "id": "c03",
    "dose": "10 vaihtelua"
   }
  ]
 },
 "coreBase2": {
  "name": "Ydin 2 – pidemmät pito, terävämpi tempo",
  "kind": "core",
  "rounds": "2 kierrosta",
  "rest": "45 sekuntia lepoa liikkeiden välillä, 90 sekuntia lepoa kierrosten välillä.",
  "ex": [
   {
    "id": "c01",
    "dose": "Pidä 30–40 sekuntia."
   },
   {
    "id": "c02",
    "dose": "8 vaihtelua"
   },
   {
    "id": "c06",
    "dose": "20–25 sekuntia / puoli"
   },
   {
    "id": "c04",
    "dose": "10 toistoa"
   },
   {
    "id": "c08",
    "dose": "10 / jalka, vähemmän tukea käsille"
   },
   {
    "id": "c05",
    "dose": "kävelyreitti, 10 metriä edestakaisin"
   }
  ]
 },
 "coreBuild": {
  "name": "Ydin 3 – rakennus: sivulankkuperhe + Kööpenhamina",
  "kind": "core",
  "rounds": "2 kierrosta",
  "rest": "45 sekuntia lepoa liikkeiden välillä, 2 minuuttia lepoa kierrosten välillä.",
  "ex": [
   {
    "id": "c02",
    "dose": "10 vaihtelua"
   },
   {
    "id": "c07",
    "dose": "20 sekuntia / puoli"
   },
   {
    "id": "c09",
    "dose": "15–20 sekuntia / puoli (ensin muutaman viikon ajan jalka lattialla)"
   },
   {
    "id": "c04",
    "dose": "10 toistoa"
   },
   {
    "id": "c08",
    "dose": "10 / jalka"
   },
   {
    "id": "c03",
    "dose": "10 toistoa + 3 sekunnin pito"
   }
  ]
 },
 "coreRot1": {
  "name": "Ydin 4 – kiertolohko A",
  "kind": "core",
  "rounds": "2 kierrosta",
  "rest": "45 sekuntia lepoa liikkeiden välillä, 2 minuuttia lepoa kierrosten välillä.",
  "ex": [
   {
    "id": "c11",
    "dose": "8 / puoli"
   },
   {
    "id": "c12",
    "dose": "6 / puoli"
   },
   {
    "id": "c10",
    "dose": "8 vaihtelua"
   },
   {
    "id": "c15",
    "dose": "6 / puoli"
   },
   {
    "id": "c09",
    "dose": "20 sekuntia / puoli"
   },
   {
    "id": "c16",
    "dose": "5 / puoli (jalka lattialla)"
   }
  ]
 },
 "coreRot2": {
  "name": "Ydin 5 – kiertolohko B",
  "kind": "core",
  "rounds": "2 kierrosta",
  "rest": "40 sekuntia lepoa liikkeiden välillä, 2 minuuttia lepoa kierrosten välillä.",
  "ex": [
   {
    "id": "c10",
    "dose": "10 vaihtelua"
   },
   {
    "id": "c13",
    "dose": "6 / puoli"
   },
   {
    "id": "c14",
    "dose": "8 toistoa"
   },
   {
    "id": "c15",
    "dose": "8 / puoli"
   },
   {
    "id": "c11",
    "dose": "10 / puoli"
   },
   {
    "id": "c16",
    "dose": "8 / puoli (sääri alhaisessa laatikossa/tikkaissa)"
   }
  ]
 },
 "coreExpress": {
  "name": "Ydin 6 – pelaajan kokoama valikko",
  "kind": "core",
  "rounds": "2 kierrosta",
  "rest": "pelaajat asettavat omat (valmentaja tarkistaa: vähintään 30 sekuntia)",
  "note": "Jokainen pelaaja valitsee 6 liikettä koko perusliikekirjastosta (katso <a href='exercises.html'>liikekirjasto</a>): <b>1 liike, joka estää vartalon kiertymistä</b> (lankku/sivulankku -tyyppiset liikkeet) + <b>1 liike, joka aktivoi lonkan ja pakaralihakset</b> (pakara-takareisiliike, supermiesliike, pakaralihaksen nosto) + <b>1 kiertoliike</b> (Spiderman-liike, vartalon kierto käsien läpi, 90-90-työntö, kyykkykierto) + <b>3 vapaavalintaista liikettä</b> (pelaajia kannustetaan valitsemaan liikkeitä, joissa he ovat heikoimpia). Toistomäärä: 8–12 toistoa tai 20–30 sekunnin pito. Valmentaja tarkistaa harjoitusohjelman ennen sen aloittamista.",
  "ex": []
 },
 "lbsBase1": {
  "name": "Reidet 1 – perusliikkeet molemmille jaloille",
  "kind": "lbs",
  "rounds": "2 sarjaa",
  "rest": "60 sekuntia lepoa liikkeiden välillä",
  "ex": [
   {
    "id": "l01",
    "dose": "6 / jalka"
   },
   {
    "id": "l02",
    "dose": "6 / jalka"
   },
   {
    "id": "l07",
    "dose": "6 / jalka — MATALA asento (alhaisin asento)"
   },
   {
    "id": "l08",
    "dose": "6 / puoli"
   }
  ]
 },
 "lbsBase2": {
  "name": "Reidet 2 – perusliikkeet isommalla liikeradalla",
  "kind": "lbs",
  "rounds": "2 sarjaa",
  "rest": "60–75 sekuntia lepoa liikkeiden välillä",
  "ex": [
   {
    "id": "l01",
    "dose": "6 / jalka — etujalka alimmalla tikasaskelmalla"
   },
   {
    "id": "l02",
    "dose": "6/jalka, hidasta 3 sekuntia"
   },
   {
    "id": "l07",
    "dose": "6 / jalka — nosta laatikkoa yhdellä pykälällä"
   },
   {
    "id": "l08",
    "dose": "6 / puoli, istu syvemmälle"
   },
   {
    "id": "l05",
    "dose": "4 toistoa per jalka — kyykky korkean laatikon päälle (alkuosa)"
   }
  ]
 },
 "lbsUni1": {
  "name": "Reidet 3 – yksijalkaisten alkeet",
  "kind": "lbs",
  "rounds": "2 sarjaa",
  "rest": "75 sekuntia lepoa liikkeiden välillä",
  "ex": [
   {
    "id": "l04",
    "dose": "5 / jalka — takajalka tikkailla"
   },
   {
    "id": "l06",
    "dose": "4/jalka — korkean laatikon päälle"
   },
   {
    "id": "l05",
    "dose": "5 / jalka — keskikokoinen laatikko"
   },
   {
    "id": "l07",
    "dose": "5 / jalka — keskikokoinen laatikko"
   },
   {
    "id": "l08",
    "dose": "6 / puoli"
   }
  ]
 },
 "lbsUni2": {
  "name": "Reidet 4 – yksijalka, syvempään",
  "kind": "lbs",
  "rounds": "2–3 sarjaa",
  "rest": "90 sekuntia lepoa liikkeiden välillä",
  "ex": [
   {
    "id": "l04",
    "dose": "6 / jalka — alempi tikkaan askelma"
   },
   {
    "id": "l06",
    "dose": "5 / jalka — alhaisempi arvo kuin viime viikolla"
   },
   {
    "id": "l05",
    "dose": "5 / jalka — alempi laatikko"
   },
   {
    "id": "l07",
    "dose": "6 askelta per jalka – korkeampi askel"
   },
   {
    "id": "l08",
    "dose": "6 / puoli + kevyt laukku"
   }
  ]
 },
 "lbsRot1": {
  "name": "Reidet 5 – kierto ja hallinta",
  "kind": "lbs",
  "rounds": "2 sarjaa",
  "rest": "75 sekuntia lepoa liikkeiden välillä",
  "ex": [
   {
    "id": "l03",
    "dose": "5 / jalka"
   },
   {
    "id": "l05",
    "dose": "5 / jalka — syvä"
   },
   {
    "id": "l08",
    "dose": "6 / puoli + kevyt laukku"
   },
   {
    "id": "x01",
    "dose": "5 toistoa per puoli — kehonpainoharjoitus"
   },
   {
    "id": "l07",
    "dose": "6 / jalka"
   }
  ]
 },
 "lbsRot2": {
  "name": "Reidet 6 – kiertolohko B",
  "kind": "lbs",
  "rounds": "2 sarjaa",
  "rest": "75–90 sekuntia lepoa liikkeiden välillä",
  "ex": [
   {
    "id": "l03",
    "dose": "6 / jalka"
   },
   {
    "id": "l06",
    "dose": "5/jalka — syvin hallittu kohta"
   },
   {
    "id": "x02",
    "dose": "5 toistoa per puoli — kehonpainoharjoitus"
   },
   {
    "id": "x03",
    "dose": "5 / jalka"
   },
   {
    "id": "l08",
    "dose": "6 / puoli"
   }
  ]
 },
 "lbsExpress": {
  "name": "Reidet 7 – yhdistä ja ilmaise (kombinaatiopiiri)",
  "kind": "lbs",
  "rounds": "2–3 kierrosta",
  "rest": "90 sekuntia lepoa liikkeiden välillä",
  "ex": [
   {
    "id": "x01",
    "dose": "5 / puoli"
   },
   {
    "id": "x02",
    "dose": "5 / puoli"
   },
   {
    "id": "x03",
    "dose": "5 / jalka"
   },
   {
    "id": "x04",
    "dose": "4 toistoa per jalka — askel ylös/alas korokkeelle"
   },
   {
    "id": "x05",
    "dose": "5 / jalka — olkapäät patjojen päällä"
   },
   {
    "id": "x06",
    "dose": "5 (kuormittamaton)"
   }
  ]
 },
 "prep1": {
  "name": "Alkuvalmistelu ja laskeutumiskoulu (vaihe 1 – ei vielä hyppyjä)",
  "kind": "power",
  "rounds": "3 lohkoa",
  "rest": "täysi hengähdystauko jaksojen välissä",
  "ex": [
   {
    "id": "p01",
    "dose": "3 toistoa × 3 / jalka — hidas, voimakas käsien liike, pysähdy jokaisen askeleen lopussa."
   },
   {
    "id": "m06",
    "dose": "4 toistoa per puoli — lankkuasennosta eteenpäin askeltava liike, jossa keskitytään liikkeen \"vaimentamiseen\"."
   },
   {
    "id": "l07",
    "dose": "3/jalka alhaalta tulevasta laatikosta – hiljainen laskeutumisharjoitus."
   }
  ]
 },
 "powA": {
  "name": "Teho A – eteenpaino (intro)",
  "kind": "power",
  "rounds": "katso per harjoitus",
  "rest": "60–90 sekuntia sarjojen välillä – pitkät lepoajat ovat tärkeimmät.",
  "ex": [
   {
    "id": "p01",
    "dose": "2 × 3 / jalka"
   },
   {
    "id": "p02",
    "dose": "2 × 3 — vain matala peti, patjat pedin ympärillä/edessä"
   },
   {
    "id": "p04",
    "dose": "2 × 3 – nollaa jokainen hyppy"
   }
  ]
 },
 "powB": {
  "name": "Teho B – sivu ja kierto",
  "kind": "power",
  "rounds": "katso per harjoitus",
  "rest": "90 sekuntia sarjojen välissä",
  "ex": [
   {
    "id": "p02",
    "dose": "2 × 3 – nosta laatikkoa yhdellä pykälällä, jos laskeutumiset olivat äänettömiä"
   },
   {
    "id": "p03",
    "dose": "2 × 3 – matala laatikko, 90 asteen kulma"
   },
   {
    "id": "p04",
    "dose": "2 × 2 jatkuva"
   },
   {
    "id": "p06",
    "dose": "2 × 3 / puoli"
   }
  ]
 },
 "powC": {
  "name": "Teho C – ilmaisu, maksimiteho",
  "kind": "power",
  "rounds": "katso per harjoitus",
  "rest": "90–120 sekuntia sarjojen välillä",
  "ex": [
   {
    "id": "p03",
    "dose": "3 × 3 — korkein laatikko, jossa on äänettömät laskeutumisalustat"
   },
   {
    "id": "p05",
    "dose": "2 × 3 / puoli — vain kevyt laukku, jos p06 on täydellinen"
   },
   {
    "id": "p06",
    "dose": "3 × 3 / puoli — nopein laskuri"
   },
   {
    "id": "p04",
    "dose": "2 × 3 (P4-venytys: 2 × 2 yksijalkainen)"
   }
  ]
 }
};
const GAMES = {
 "rondo41": {
  "n": "Rondo-harjoitus: 4 vastaan 1 → 5 vastaan 1 → 5 vastaan 2",
  "balls": "1",
  "how": "4–5 pelaajaa pitää palloa 5–6 metrin neliön sisällä, 1–2 pelaajaa keskellä. Piste: 3 onnistunutta syöttöä → vaihdetaan puolustajat. Kun pelaajat ovat tottuneet harjoitukseen, enintään 2 kosketusta, oppimisvaiheessa 3 kosketusta.",
  "space": "Yksi verhoalue, kartion muotoinen neliö"
 },
 "boxgame": {
  "n": "Laatikkopeli 3v3 / 4v4",
  "balls": "1",
  "how": "Pelaa 8 x 8 metrin kokoisella alueella, jonka kummassakin päässä on pieni maali (tai lippumaalit). Maali lasketaan vain, jos se on tehty alueen sisällä. Kaikki pelaavat kaikkialla.",
  "space": "Yksi alue, 2 pientä maalia + 4 kartiota."
 },
 "king": {
  "n": "Laatikon kuningas",
  "balls": "1",
  "how": "4 vastaan 4, yksi pallo, enintään 6 syöttöä per hyökkäys – maalit on tehtävä liikkeessä, ei potkaisemalla palloa aloituspotkusta. Voittajat jatkavat, häviäjät osallistuvat seuraavaan haasteeseen.",
  "space": "Yksi alue, 2 pientä maalia."
 },
 "shadow": {
  "n": "Varjokilpailut",
  "balls": "0",
  "how": "Parileikki: peilileima 6 x 6 metrin alueella, 30 sekunnin kierrokset; häviäjä kerää kartiot. Pelkkää suunnanvaihtoleikkiä – ei hyppimistä.",
  "space": "Yksi alue, kartiot"
 },
 "gauntlet": {
  "n": "Estaviesti (yksinkertainen rata)",
  "balls": "0–1",
  "how": "Tikkaat → 6 aitaa (astutaan yli, ei saa kaataa) → askelharjoitus laatikon päälle/alas → roikku 5 sekuntia → juokse patjaan ja pidä jäätynyttä lankkua 3 sekuntia. Joukkueviesti, vuorotellen eri tehtävissä.",
  "space": "Yhden vyöhykkeen koko leveys"
 },
 "ropegames": {
  "n": "Köysipelit",
  "balls": "0",
  "how": "Riippuvassa köydessä tehtävä harjoitus: 10 sekuntia roikkuen, polvet rintaan (jalat voi laittaa patjoille), parin kanssa tehtävä \"saha\"-liike, joukkueen vetoharjoitus 3 x 8 sekuntia. Kehittää pitoa, olkapäitä ja on hauskaa.",
  "space": "Kiipeilyseinäalue, alusmatot"
 },
 "minileague": {
  "n": "Miniliiga 3v3 / 4v4",
  "balls": "1–2",
  "how": "Pienikokoinen turnaus, joka pelataan kahdella alueella, ja jossa on käytössä 6 pientä maalia; ottelut kestävät 3 minuuttia, ja pisteet merkitään taulukkoon seinälle.",
  "space": "Kaksi aluetta, 4–6 pientä maalia."
 },
 "duel1v1": {
  "n": "1v1-kaksintaisteluneliö",
  "balls": "2",
  "how": "3 × 3 metrin kokoiset neliöt, 45 sekunnin mittaiset kaksintaistelut, valmentaja syöttää palloja yksi kerrallaan. Lasketaan voitot; voittaja jatkaa.",
  "space": "Pallokentän kulmat"
 },
 "pasquare": {
  "n": "Syöttöneliöt 2v2 / 3v3",
  "balls": "1 per pair",
  "how": "Kaksi riviä liikkuvia maalialueita, syöttö-kääntö-syöttö -harjoitus. Enintään 10 palloa = 10 pelaajaa, suhde 1:1.",
  "space": "Pallokenttä"
 },
 "tethers": {
  "n": "Vapaa peliaika + viikoittainen haaste",
  "balls": "2",
  "how": "Vapaata peliä alueella, jossa on kolmen kosketuksen sääntö; jakson viimeiset 3 minuuttia = viikoittainen haaste (pallo ylätankoon, pallonhallintaharjoitus 90 sekuntia, pisin lentopallo).",
  "space": "Yksi vyöhyke"
 }
};
const PHASES = [
 {
  "id": "P1",
  "wks": "1–6",
  "cls": "p1",
  "name": "Perustaidot ja liikkumistaitojen kehittäminen",
  "goal": "Hallitse perusteet ennen kuin siirryt vaikeampiin asioihin. Mikään ei saa olla hätäistä: ainoa tärkeä asia on laatu.",
  "points": [
   "Liikkuvuusharjoitus A jokaiseen alkulämmittelyyn – opeta oikea ryhti käyttämällä nimiä ja ohjeita.",
   "Keskivartalo: lankkuperhe, glute-ham -liike, marssi, istuen tehtävät ylävartalon nostot (Keskivartalo 1 → 2)",
   "Jalat: molemminpuoliset askelkyykyt, askel alas matalalta korokkeelta (Jalat 1 → 2)",
   "Tehopaikka = laskeutumiskoulu ja nopeuskilpailut – vielä ei hyppyjä.",
   "W6 = ensimmäinen testi: ajastettu ydinkytkentä + liikkeenohjausportin tarkistuslista"
  ]
 },
 {
  "id": "P2",
  "wks": "7–12",
  "cls": "p2",
  "name": "Rakenna voimaa, lisää tehoa",
  "goal": "Yksi jalka, suurempi liikerata – ja ensimmäiset todelliset hypyt, uuden hermoston avulla.",
  "points": [
   "Liikkuvuussetti B – lisätty uusia liikeratoja, joissa liikutaan lankun päällä",
   "Vahvistavat lihakset: sivulankku, jalat erillään + Kööpenhaminan lankku (Vahvistavat lihakset 3)",
   "Jalat: Bulgarialainen askelkyykky tikkailla, pistolikyykky ja skater-kyykky laatikoille (Jalat 3 → 4)",
   "Koko ryhmän tehokasta mikroannostelua sisältävä alkulämmittely: tehokkaat liikkeet, matalat hyppyharjoitukset, leveät hypyt.",
   "W12 = testi + uustesti verrattuna W6:een (sama harjoitusvideo)"
  ]
 },
 {
  "id": "P3",
  "wks": "13–18",
  "cls": "p3",
  "name": "Kierto ja hallinta",
  "goal": "Pyöritys on jalkapallon perusliike: paina, leikkaa, laskeudu, käänny. Keskeiset harjoitukset ja vastusharjoitusten yhdistelmät sisällytetään harjoitusohjelmaan.",
  "points": [
   "Liikkuvuuspaketti C – sisältää täyden akun Maailman paras venyttelyharjoitus",
   "Keskeiset liikkeet: Spiderman-liike, vartalon läpi ulottuvat liikkeet, 90-90-liikkeet, Kööpenhaminan alavartalon nosto (Keskeiset liikkeet 4 → 5)",
   "Jalat: ylävartalon taakse suuntautuvat askelkyykyt + ensimmäiset yhdistelmäliikkeet, kumarre → sivuttaiskyykky ja kiertoliike (Jalat 5 → 6)",
   "Voima: pyörivät hyppyharjoitukset + nopeat sivuttaiset vastaliikkeet (Voima B)",
   "W18 = testi + uustesti verrattuna W6/W12"
  ]
 },
 {
  "id": "P4",
  "wks": "19–24",
  "cls": "p4",
  "name": "Ilmaisu ja kombinaatiot",
  "goal": "Kaikki yhdessä: kokonaisvaltaiset liikeketjut, maksimaalinen teho ja pelaajien omat pelialustat.",
  "points": [
   "Liikkuvuus: pelaajat valitsevat itse 9 liikettä joukosta C ja suorittavat niistä lämmittelysarjan.",
   "Ydinominaisuudet: pelaajan luoma valikko (Core 6) + yhteistyöhaasteet",
   "Jalat: kuusi liikettä yhdistettynä yhdeksi sarjaksi (Jalat 7) – keskitytään kehonpainoharjoitteluun, käytä kevyitä painoja vain, jos tekniikka on täydellistä.",
   "Power C: paras äänetön laskeutumislaatikko, nopeimmat vastahyökkäykset (Power C)",
   "W23 = viimeinen testisarja; W24 = festivaali + kauden yhteenveto"
  ]
 }
];
